apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  {{ if .Values.postgres.enabled }}
  postgres_db: {{ .Values.global.postgresql.postgresqlDatabase }}
  postgres_user: {{ .Values.global.postgresql.postgresqlUsername }}
  postgres_port: {{ quote .Values.global.postgresql.postgresqlServicePort }}
  postgres_host: {{ .Release.Name }}-postgresql
  {{ end }}
